python main_program_one_depth_cascade.py --instance_location instance30 --budget 26.3 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 11 --line_establish_capacity_coef_scale 22 --line_establish_cost_coef_scale 1 --dump_file 1
python robustness_heuristic_upper_bound.py --instance_location instance30 --budget 26.3 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --dump_file 17
python main_program.py --instance_location instance30 --budget 26.3 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 22 --line_upgrade_capacity_coef_scale 11 --dump_file 33
python main_program_one_depth_cascade.py --instance_location instance57 --budget 90.04 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 24 --line_establish_capacity_coef_scale 48 --line_establish_cost_coef_scale 1 --dump_file 2
python robustness_heuristic_upper_bound.py --instance_location instance57 --budget 90.04 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --dump_file 18
python main_program.py --instance_location instance57 --budget 90.04 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 48 --line_upgrade_capacity_coef_scale 24 --dump_file 34
python main_program_one_depth_cascade.py --instance_location instance118 --budget 718.06 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 50 --line_establish_capacity_coef_scale 101 --line_establish_cost_coef_scale 10 --dump_file 3
python robustness_heuristic_upper_bound.py --instance_location instance118 --budget 718.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --dump_file 19
python main_program.py --instance_location instance118 --budget 718.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 101 --line_upgrade_capacity_coef_scale 50 --dump_file 35
python main_program_one_depth_cascade.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 143 --line_establish_capacity_coef_scale 286 --line_establish_cost_coef_scale 10 --dump_file 4
python robustness_heuristic_upper_bound.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --dump_file 20
python main_program.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 286 --line_upgrade_capacity_coef_scale 143 --dump_file 36
python main_program_one_depth_cascade.py --instance_location instance30 --budget 39.45 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 11 --line_establish_capacity_coef_scale 22 --line_establish_cost_coef_scale 1 --dump_file 5
python robustness_heuristic_upper_bound.py --instance_location instance30 --budget 39.45 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --dump_file 21
python main_program.py --instance_location instance30 --budget 39.45 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 22 --line_upgrade_capacity_coef_scale 11 --dump_file 37
python main_program_one_depth_cascade.py --instance_location instance57 --budget 135.06 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 24 --line_establish_capacity_coef_scale 48 --line_establish_cost_coef_scale 1 --dump_file 6
python robustness_heuristic_upper_bound.py --instance_location instance57 --budget 135.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --dump_file 22
python main_program.py --instance_location instance57 --budget 135.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 48 --line_upgrade_capacity_coef_scale 24 --dump_file 38
python main_program_one_depth_cascade.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 50 --line_establish_capacity_coef_scale 101 --line_establish_cost_coef_scale 10 --dump_file 7
python robustness_heuristic_upper_bound.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --dump_file 23
python main_program.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 101 --line_upgrade_capacity_coef_scale 50 --dump_file 39
python main_program_one_depth_cascade.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 1 --line_upgrade_capacity_upper_bound 143 --line_establish_capacity_coef_scale 286 --line_establish_cost_coef_scale 10 --dump_file 8
python robustness_heuristic_upper_bound.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --dump_file 24
python main_program.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 1 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 286 --line_upgrade_capacity_coef_scale 143 --dump_file 40
python main_program_one_depth_cascade.py --instance_location instance30 --budget 26.3 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 11 --line_establish_capacity_coef_scale 22 --line_establish_cost_coef_scale 1 --dump_file 9
python robustness_heuristic_upper_bound.py --instance_location instance30 --budget 26.3 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --dump_file 25
python main_program.py --instance_location instance30 --budget 26.3 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 22 --line_upgrade_capacity_coef_scale 11 --dump_file 41
python main_program_one_depth_cascade.py --instance_location instance57 --budget 90.04 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 24 --line_establish_capacity_coef_scale 48 --line_establish_cost_coef_scale 1 --dump_file 10
python robustness_heuristic_upper_bound.py --instance_location instance57 --budget 90.04 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --dump_file 26
python main_program.py --instance_location instance57 --budget 90.04 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 48 --line_upgrade_capacity_coef_scale 24 --dump_file 42
python main_program_one_depth_cascade.py --instance_location instance118 --budget 718.06 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 50 --line_establish_capacity_coef_scale 101 --line_establish_cost_coef_scale 10 --dump_file 11
python robustness_heuristic_upper_bound.py --instance_location instance118 --budget 718.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --dump_file 27
python main_program.py --instance_location instance118 --budget 718.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 101 --line_upgrade_capacity_coef_scale 50 --dump_file 43
python main_program_one_depth_cascade.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 143 --line_establish_capacity_coef_scale 286 --line_establish_cost_coef_scale 10 --dump_file 12
python robustness_heuristic_upper_bound.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --dump_file 28
python main_program.py --instance_location instance300 --budget 3158.04 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 286 --line_upgrade_capacity_coef_scale 143 --dump_file 44
python main_program_one_depth_cascade.py --instance_location instance30 --budget 39.45 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 11 --line_establish_capacity_coef_scale 22 --line_establish_cost_coef_scale 1 --dump_file 13
python robustness_heuristic_upper_bound.py --instance_location instance30 --budget 39.45 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --dump_file 29
python main_program.py --instance_location instance30 --budget 39.45 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 22 --line_upgrade_capacity_coef_scale 11 --dump_file 45
python main_program_one_depth_cascade.py --instance_location instance57 --budget 135.06 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 24 --line_establish_capacity_coef_scale 48 --line_establish_cost_coef_scale 1 --dump_file 14
python robustness_heuristic_upper_bound.py --instance_location instance57 --budget 135.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --dump_file 30
python main_program.py --instance_location instance57 --budget 135.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 1 --line_establish_capacity_coef_scale 48 --line_upgrade_capacity_coef_scale 24 --dump_file 46
python main_program_one_depth_cascade.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 50 --line_establish_capacity_coef_scale 101 --line_establish_cost_coef_scale 10 --dump_file 15
python robustness_heuristic_upper_bound.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --dump_file 31
python main_program.py --instance_location instance118 --budget 1077.09 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 101 --line_upgrade_capacity_coef_scale 50 --dump_file 47
python main_program_one_depth_cascade.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 0.8 --line_upgrade_capacity_upper_bound 143 --line_establish_capacity_coef_scale 286 --line_establish_cost_coef_scale 10 --dump_file 16
python robustness_heuristic_upper_bound.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --dump_file 32
python main_program.py --instance_location instance300 --budget 4737.06 --load_capacity_factor 0.8 --line_establish_cost_coef_scale 10 --line_establish_capacity_coef_scale 286 --line_upgrade_capacity_coef_scale 143 --dump_file 48
