python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance24 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 10 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 25 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.25 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 5 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 15 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 50 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 100 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
python robustness_heuristic.py --instance_location instance300 --budget 200 --upgrade_selection_bias 0.5 --min_neighbors 50 --export_results_tracking c:\temp\grid_cascade_output\hr_res_apollo.csv
